<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>UTMS.Core</RootNamespace>
    <AssemblyName>UTMS.Core</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="BinaryCode.cs" />
    <Compile Include="Properties\Settings.Designer.cs" />
    <Compile Include="SyntaxChecker.cs" />
    <Compile Include="TuringMachine.cs" />
    <Compile Include="TuringMachineDefinition.cs" />
    <Compile Include="TuringMachineDefinitionLoader.cs" />
    <Compile Include="TuringMachineGraphExporter.cs" />
    <Compile Include="TuringMachineProgram.cs" />
    <Compile Include="TuringMachineProgramSerializer.cs" />
    <Compile Include="TuringSimulator.cs" />
  </ItemGroup>
</Project>
